### PR TITLE
[Browser] Improve usability by showing in/out arc dcid

### PR DESCRIPTION
**Pull request by shifucun**
When I look up stat var property in browser, turns out the display text is different from enum, which is not obvious. Even if user knows it, has to click in to copy the dcid. This is try to improve that by showing the dcid as well. It makes a row a bit busier but makes it more clear and easy to use.

image

### CODE REVIEW

**Comment by shifucun** [comment]
Using smaller font weight now

**Comment by shifucun** [comment]
@beets PTAL

**Review by beets — APPROVED** [review]
sorry missed this. thx for the update!

**Comment by shifucun** [comment]
thanks!

**Pull request merged**
