### PR TITLE
[Library] Stacked and Horizontal Lollipop Charts

### PR DESCRIPTION
**Pull request by juliawu**
This PR adds the ability to draw stacked and horizontal lollipop charts, and updates the docs/examples.

Examples (compare to bar version):
```
  <datacommons-bar
    title="Median income by gender for counties in Alaska (horizontal, stacked, lollipop)"
    comparisonVariables="Median_Income_Person Median_Income_Person_15OrMoreYears_Male_WithIncome Median_Income_Person_15OrMoreYears_Female_WithIncome"
    place="geoId/02"
    childPlaceType="County"
    lollipop
    horizontal
    stacked
  ></datacommons-bar>
```
Screenshot 2023-07-12 at 9 15 18 AM

```
<datacommons-bar
  title="Median income by gender of select US states (stacked, lollipop)"
  comparisonVariables="Median_Income_Person_15OrMoreYears_Male_WithIncome Median_Income_Person_15OrMoreYears_Female_WithIncome"
  comparisonPlaces="geoId/01 geoId/02 geoId/04 geoId/05"
  stacked
  lollipop
></datacommons-bar>
```
Screenshot 2023-07-12 at 9 15 10 AM

### CODE REVIEW

**Comment by pradh** [comment]
nit: Any way to avoid the place names being cut off in the horizontal charts?

**Comment by juliawu** [comment]
> nit: Any way to avoid the place names being cut off in the horizontal charts?

There's a `yAxisMargin` attribute that lets users expand that distance if they see place names being cut off.

@dwnoble @shifucun and I were discussing a better long term fix -- it's looking like a bigger change, so once we settle on the approach we'll add that in a future PR.

**Review by dwnoble — APPROVED** [review]
Nice! Do horizontal lollipop charts render properly when setting the `barHeight` attribute on the web component? (they should get spaced closer together)

**Comment by dwnoble** [comment]
> > nit: Any way to avoid the place names being cut off in the horizontal charts?
> 
> There's a `yAxisMargin` attribute that lets users expand that distance if they see place names being cut off.
> 
> @dwnoble @shifucun and I were discussing a better long term fix -- it's looking like a bigger change, so once we settle on the approach we'll add that in a future PR.

Agreed the current behavior isn't ideal - we can come up with more sensible way to show the labels without cutting off the text in the future

**Comment by juliawu** [comment]
> Do horizontal lollipop charts render properly when setting the barHeight attribute on the web component? 

Double checked: yes! Lollipops get closer together if we reduce barHeight.

**Pull request merged**
