### PR TITLE
Various updates based on recent mixer change

### PR DESCRIPTION
**Pull request by shifucun**
- Move schema mapping as config
- Use branch BT table
- grpc descriptor path change
- Reduce Memory/CPU change request size based on monitoring, this prepares for auto-scaling
- New cluster deploy script
- SSL domain includes all sub-domains

---
This change is [Reviewable](https://reviewable.io/reviews/datacommonsorg/website/777)

### CODE REVIEW

**Review by pradh — CHANGES_REQUESTED** [review]
Please note that before we enable BT table we should probably find a way to test in staging env. So I wonder if it might be worth separating out the completion file and channel between prod and staging?

Also, note that the borg controller needs some tweaks for it to start writing the BT name on completion. And that change needs to be synchronized with prod.

> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/website/777#-:-MR_ljKb0Sel5vGkdX4K:b3l1sal)* status: 0 of 11 files reviewed, all discussions resolved (waiting on @beets)

**Comment by shifucun** [comment]
> Please note that before we enable BT table we should probably find a way to test in staging env. So I wonder if it might be worth separating out the completion file and channel between prod and staging?
> 
> Also, note that the borg controller needs some tweaks for it to start writing the BT name on completion. And that change needs to be synchronized with prod.
> 
> > _[Reviewable](https://reviewable.io/reviews/datacommonsorg/website/777#-:-MR_ljKb0Sel5vGkdX4K:b3l1sal)_ status: 0 of 11 files reviewed, all discussions resolved (waiting on @beets)

Have separate channels on staging and prod sounds good. I thought the branch table is already recorded in the version txt file and it works with the mixer already?

**Review by pradh — APPROVED** [review]
Right now it records the path to CSV files, and I think it writes it before BT table is built. Minimally, that should change to writing after BT is built.. do we also want to change its contents to just contain the BT table ?

> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/website/777#-:-MRaBpu5D6LkzD0waATe:bgie3sc)* status: 0 of 11 files reviewed, all discussions resolved (waiting on @beets)

**Review by shifucun — COMMENTED** [review]
Got it. The content is "branch_2021_01_20_14_31_09", it is the branch table?

> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/website/777#-:-MRaD7KzEqBqaZVhdphy:b-dq5lft)* status: 0 of 11 files reviewed, all discussions resolved (waiting on @beets)

**Review by beets — APPROVED** [review]

**Pull request merged**
