### PR TITLE
[vis tool] fix source selector on timeline

### PR DESCRIPTION
**Pull request by chejennifer**
This fixes the source selector for the timelines on vis tool (https://screenshot.googleplex.com/kX3735zMTDF7uFR). The problem was that the endpoint for fetching the facets enforced strict slashes, but the client was not passing in a slash and so the client was being redirected to a location it could not access.

### CODE REVIEW

**Review by shifucun — COMMENTED** [review]
should we do the same thing for other endpoints?

**Comment by chejennifer** [comment]
> should we do the same thing for other endpoints?

I did a quick search through the website repo and the other cases where the endpoint ends in a '/' are all routes for a page (e.g., /browser/) & those redirects are ok. The problem only occurs when the client tries to fetch data from an endpoint that redirects.

**Review by dwnoble — APPROVED** [review]

**Review by juliawu — APPROVED** [review]
Thanks for the fix!

**Comment by chejennifer** [comment]
thanks for the reviews!

**Pull request merged**
