### PR TITLE
Website server start should check mixer readiness

### PR DESCRIPTION
**Pull request by shifucun**

### CODE REVIEW

**Review by beets — APPROVED** [review]
thanks for this!

**Comment by beets** [comment]
the two codeql errors look like good candidates for a fix, but they are not related to the PR at all.

**Review by pradh — APPROVED** [review]

**Comment by shifucun** [comment]
> the two codeql errors look like good candidates for a fix, but they are not related to the PR at all.

Okay, looks like they are not trivial to fix. Going to look at the codeql errors in batch later.

**Comment by shifucun** [comment]
Thanks for review!

**Pull request merged**
