### PR TITLE
Import translated strings for place pages from TC

### PR DESCRIPTION
**Pull request by beets**
This gets us most of the way there, though there are still lots to do.

Outstanding TODOs:
- Add some straggler strings to TC for translation
- Figure out how to handle territory in babel (pybabel complains about zh-CN and pt-BR, but this is the hl format we'd like)
- Figure out how to compile per-locale JS bundles || import the translated stat var titles 
- Improve hl parsing code

Chicago page, in French. Will look much better once #756 is in
image

---
This change is [Reviewable](https://reviewable.io/reviews/datacommonsorg/website/758)

### CODE REVIEW

**Review by hanlu09205 — APPROVED** [review]
> Reviewed 61 of 61 files at r1.
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/website/758)* status: all files reviewed, 1 unresolved discussion (waiting on @beets)

___
*[server/__init__.py, line 137 at r1](https://reviewable.io/reviews/datacommonsorg/website/758#-MQVTI1b3h5bIKedJ8Dq:-MQVTI1b3h5bIKedJ8Dr:b-1m3ol8) ([raw file](https://github.com/datacommonsorg/website/blob/bd87f2d5ea34e6686d186d32b5dd9782aba760f4/server/__init__.py#L137)):*
> ```Python
>     def before_request():
>         # TODO(beets): Also use request.accept_languages.best_match()
>         # - Use Locale.negotiate, and use - instead of _ separators
> ```

Nit, not sure I understand this exactly, but since it's TODO under u, shall be fine :)

**Review by beets — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/website/758)* status: all files reviewed, 1 unresolved discussion (waiting on @hanlu09205)

___
*[server/__init__.py, line 137 at r1](https://reviewable.io/reviews/datacommonsorg/website/758#-MQVTI1b3h5bIKedJ8Dq:-MQY4UvMEWwByPzdohFN:bi76ano) ([raw file](https://github.com/datacommonsorg/website/blob/bd87f2d5ea34e6686d186d32b5dd9782aba760f4/server/__init__.py#L137)):*
<details><summary><i>Previously, hanlu09205 wrote…</i></summary><blockquote>

Nit, not sure I understand this exactly, but since it's TODO under u, shall be fine :)
</blockquote></details>

It refers to a few things:
- some validation of the passed in hl parameter
- if using babel libraries for that, try to handle - instead of _ separators (you'll note that instead of zh-CN, we have zh_Hans_CN which is used by default, which is not what we want :-/)

**Review by hanlu09205 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/website/758)* status: all files reviewed, 1 unresolved discussion (waiting on @beets)

___
*[server/__init__.py, line 137 at r1](https://reviewable.io/reviews/datacommonsorg/website/758#-MQVTI1b3h5bIKedJ8Dq:-MQY6HaKEwZRLzBWrOiB:b-wsvasg) ([raw file](https://github.com/datacommonsorg/website/blob/bd87f2d5ea34e6686d186d32b5dd9782aba760f4/server/__init__.py#L137)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

It refers to a few things:
- some validation of the passed in hl parameter
- if using babel libraries for that, try to handle - instead of _ separators (you'll note that instead of zh-CN, we have zh_Hans_CN which is used by default, which is not what we want :-/)
</blockquote></details>

Thanks for the explanation!

**Comment by beets** [comment]
Here is a latest screenshot, post merge, showing chart title translations.
Some minor code updates to fix py tests.

image

**Pull request merged**
