### PR TITLE
Add more screenshot urls

### PR DESCRIPTION
**Pull request by pradh**

### CODE REVIEW

**Review by shifucun — APPROVED** [review]
Nice! Can you run it locally with `./run_test.sh -s` and check the generated screenshot under /screenshots folder?

**Comment by pradh** [comment]
> Nice! Can you run it locally with `./run_test.sh -s` and check the generated screenshot under /screenshots folder?

I see one timeout exception, and its not obvious from where.  How do you debug it?

```
>     self.assertTrue(runner.run(self.driver, self.url_, 'local'))

server/webdriver/screenshot/local/test_run.py:24: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
server/webdriver/screenshot/runner.py:52: in run
    WebDriverWait(driver, shared.TIMEOUT).until(shared.charts_rendered)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <selenium.webdriver.support.wait.WebDriverWait (session="7276c616f0dd30dcb1b0db7e81446e19")>, method = <function charts_rendered at 0x113aa7880>, message = ''

    def until(self, method, message: str = ""):
        """Calls the method provided with the driver as an argument until the \
        return value does not evaluate to ``False``.
    
        :param method: callable(WebDriver)
        :param message: optional message for :exc:`TimeoutException`
        :returns: the result of the last call to `method`
        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs
        """
        screen = None
        stacktrace = None
    
        end_time = time.monotonic() + self._timeout
        while True:
            try:
                value = method(self._driver)
                if value:
                    return value
            except self._ignored_exceptions as exc:
                screen = getattr(exc, "screen", None)
                stacktrace = getattr(exc, "stacktrace", None)
            time.sleep(self._poll)
            if time.monotonic() > end_time:
                break
>       raise TimeoutException(message, screen, stacktrace)
E       selenium.common.exceptions.TimeoutException: Message:

.env/lib/python3.11/site-packages/selenium/webdriver/support/wait.py:95: TimeoutException
--------------------------------------------------------------------------- Captured stdout setup ---------------------------------------------------------------------------
```

**Comment by shifucun** [comment]
Feel free to submit this and I can debug later. Need to log the error case url in logging properly

**Comment by pradh** [comment]
> Feel free to submit this and I can debug later. Need to log the error case url in logging properly

Thanks!

**Pull request merged**
