### PR TITLE
Update NL integration test goldens

### PR DESCRIPTION
**Pull request by juliawu**
Updates our NL integration test goldens via `./run_test.sh -g`.

Per our release docs, our NL tests rely on staging mixer, so the goldens need to be updated after a mixer release to staging. These updated goldens reflect the data changes from this mixer commit: https://github.com/datacommonsorg/mixer/commit/75c03483a4e843bb77ad71c3e0a6694a2ff39dd0

### CODE REVIEW

**Comment by juliawu** [comment]
@chejennifer @pradh These changes just look like floating point error-esque differences. Do we need this update?

**Review by chejennifer — COMMENTED** [review]
thanks! but did you mean to include the mixer submodule change?

**Comment by juliawu** [comment]
> thanks! but did you mean to include the mixer submodule change?

Yup, wanted to keep the changes together with the mixer version that generated these files -- was waiting on https://github.com/datacommonsorg/website/pull/4522 to merge. The mixer change diffs have gone away after updating the branch with latest changes.

**Review by chejennifer — APPROVED** [review]
thanks for updating!

**Pull request merged**
