### PR TITLE
[NL] add svpg descriptions to blocks

### PR DESCRIPTION
**Pull request by beets**
also updated color of fires (swapped with extreme heat, which is now a darker yellow)
image
image

image
image

### CODE REVIEW

**Review by pradh — APPROVED** [review]
Nice!  Thank you!

**Comment by beets** [comment]
one more fix for the map height:
image

partial fix for disaster map:
image

**Comment by beets** [comment]
(will merge this in first so we can iterate)

**Comment by pradh** [comment]
Perfect!  In the event picture, the map now seems a bit small?

**Comment by beets** [comment]
> Perfect! In the event picture, the map now seems a bit small?

Yes - not quite sure what's happening there.. will look into it more

**Pull request merged**
