### PR TITLE
Add a config to get titles for select StatVars for the NL page.

### PR DESCRIPTION
**Pull request by pulkit-s**
Add a config to get titles for select StatVars.

### CODE REVIEW

**Comment by pulkit-s** [comment]
The failing code quality analysis is weird . I guess the indentation of this file is 2 units and it wants it to be 4 units. (https://screenshot.googleplex.com/66zpsw4sCLZ3vWg.png)

**Review by chejennifer — APPROVED** [review]
thanks for the change!

**Comment by chejennifer** [comment]
> The failing code quality analysis is weird . I guess the indentation of this file is 2 units and it wants it to be 4 units. (https://screenshot.googleplex.com/66zpsw4sCLZ3vWg.png)

I think if you've run the linter on the code (`./run_test.sh -f`), should be fine!

**Comment by pulkit-s** [comment]
> 

I did run that, so we should be good.

**Pull request merged**
