### PR TITLE
Fix some missing data issue

### PR DESCRIPTION
**Pull request by shifucun**
Remove continent from parent places.
Remove null data from bar chart.
Add % as unit for unemployment rate.

### CODE REVIEW

**Review by beets — COMMENTED** [review]
Did this trigger any d3 warnings in the console? Iirc, it was a naive fix to clear those warnings for stacked bar charts with null values.

**Comment by shifucun** [comment]
> Did this trigger any d3 warnings in the console? Iirc, it was a naive fix to clear those warnings for stacked bar charts with null values.

I do not see console warnings. This is for a single bar chart case: 
image do you think the d3 warnings apply here?

**Comment by beets** [comment]
The warnings were for stacked bar charts.

**Review by beets — DISMISSED** [review]

**Comment by beets** [comment]
There's a test that needs to be fixed tho

**Comment by shifucun** [comment]
> There's a test that needs to be fixed tho

The tests are very comprehensive now.

**Review by beets — APPROVED** [review]

**Pull request merged**
