### PR TITLE
Removed 'Analyze this data in BigQuery' button from visualization tools

### PR DESCRIPTION
**Pull request by dwnoble**
## Before
before1
after2

## After
after1
before2

### CODE REVIEW

**Comment by n-h-diaz** [comment]
Thanks for doing this! Could you wait on submitting this for now? I think the usage dashboard I was looking at earlier wasn't updated/out-of-date, so want to double check with Prem

**Comment by n-h-diaz** [comment]
> Thanks for doing this! Could you wait on submitting this for now? I think the usage dashboard I was looking at earlier wasn't updated/out-of-date, so want to double check with Prem

Just checked with Prem and looks like we're good to disable for now, thanks!

**Comment by dwnoble** [comment]
> > Thanks for doing this! Could you wait on submitting this for now? I think the usage dashboard I was looking at earlier wasn't updated/out-of-date, so want to double check with Prem
> 
> Just checked with Prem and looks like we're good to disable for now, thanks!

Sounds good-thanks Natalie!

**Review by chejennifer — APPROVED** [review]
nice!

**Pull request merged**
