### PR TITLE
Redesign merge

### PR DESCRIPTION
**Pull request by beets**
Merge in changes from the redesign branch to master.

### CODE REVIEW

**Comment by shifucun** [comment]
@googlebot I signed it!

**Review by shifucun — DISMISSED** [review]
Took a brief look and did not see major issues. Might let it release to staging and start test there..

**Comment by beets** [comment]
Yea, I agree. I was careful merging but there were quite a few conflicts. Let's test on staging.

@qlj-lijuan @wh1210 - could you both help with the CLA warning? Thanks!

**Comment by shifucun** [comment]
@googlebot I fixed it.

**Comment by beets** [comment]
@googlebot I fixed it

**Comment by wh1210** [comment]
@googlebot I fixed it

**Comment by qlj-lijuan** [comment]
@googlebot I fixed it

**Comment by beets** [comment]
@pradh @tjann could you also please retrigger googlebot? Thanks!

**Comment by tjann** [comment]
@googlebot I signed it!

**Comment by beets** [comment]
Thanks all - I'm not sure what's wrong with the CLA and see no way to fix it :( 
I'm going to make this a draft and send you a new PR.

**Comment by shifucun** [comment]
took the bot a day to respond ...

**Comment by tjann** [comment]
big sad...

**Comment by beets** [comment]
I actually reached out to the team late last night, and they fixed it immediately today! And probably retriggered on open PRs. It was a parse error, probably from the merge.

**Pull request closed without merging**
