### PR TITLE
Redesign merge

### PR DESCRIPTION
**Pull request by beets**
Merge master from PR #65 - 476d53b32875ecf88827a33881381893fc2f2f8b

### CODE REVIEW

**Comment by beets** [comment]
@googlebot I signed it!

**Comment by beets** [comment]
@wh1210 @qlj-lijuan could you reply with "@googlebot I signed it!" to see if that helps? You're also authors of this merge. Thanks!

**Comment by wh1210** [comment]
@googlebot  I signed it!

**Comment by shifucun** [comment]
@googlebot I signed it!

**Comment by shifucun** [comment]
This is awesome!

**Comment by qlj-lijuan** [comment]
@googlebot I signed it!

**Comment by qlj-lijuan** [comment]
@googlebot I fixed it.

**Comment by beets** [comment]
Thanks all!

**Pull request merged**
