### PR TITLE
[sdg] some homepage updates

### PR DESCRIPTION
**Pull request by chejennifer**
- remove replace search with dc logo in the header
- update line size

Screenshot 2023-09-13 at 11 48 49 AM

### CODE REVIEW

**Review by juliawu — APPROVED** [review]
Thanks!

**Comment by dwnoble** [comment]
@chejennifer can you replace the search box with this? 
9JSgGxox6Nce6bi
(and fix the alignment-it looks like that blue image is off by a pixel or two)

**Comment by chejennifer** [comment]
> @chejennifer can you replace the search box with this? 9JSgGxox6Nce6bi (and fix the alignment-it looks like that blue image is off by a pixel or two)

updated

**Review by dwnoble — APPROVED** [review]

**Comment by chejennifer** [comment]
thanks for the reviews!

**Pull request merged**
