### PR TITLE
Update NL golden; Speed up test with -n 3

### PR DESCRIPTION
**Pull request by shifucun**

### CODE REVIEW

**Review by pradh — APPROVED** [review]
Nice!

**Comment by jehangiramjad** [comment]
Please run $rm - r ~/.datacommons to clear the cache. Otherwise, your local server will continue to use to old cached embeddings :) The embeddings were updated. Once you clear the cache, please run the integration tests update again.

**Comment by shifucun** [comment]
> Please run $rm - r ~/.datacommons to clear the cache. Otherwise, your local server will continue to use to old cached embeddings :) The embeddings were updated. Once you clear the cache, please run the integration tests update again.

Done

**Review by jehangiramjad — APPROVED** [review]

**Comment by pradh** [comment]
Nice find Jehangir!!

**Pull request merged**
