### PR TITLE
[nodejs] fixes for bard

### PR DESCRIPTION
**Pull request by chejennifer**
- fix legend spacing caused by docker container not having the roboto font
    - currently on bard instance: https://screenshot.googleplex.com/45bPUnBwDMyt24p
    - dev instance (with dockerfile change pushed): https://screenshot.googleplex.com/88H8LYyuXGq6rxA
- add a white background
    - current when we remove the img container background: https://screenshot.googleplex.com/7eqmEUTJDAp9mrv
    - with the change if we remove the img container background: https://screenshot.googleplex.com/C9wxCqjYFiPTBnH

### CODE REVIEW

**Comment by pradh** [comment]
Thanks.  Maybe attach before / after example charts?

**Comment by chejennifer** [comment]
> Thanks. Maybe attach before / after example charts?

added to the description!

**Review by pradh — APPROVED** [review]
Tentative LG for a deferred review to get this in for Bard evals.

**Comment by chejennifer** [comment]
thanks for the review! & for other reviewers, feel free to still leave comments and I can address them in a future PR

**Pull request merged**
