### PR TITLE
Prettier and @typescript-eslint package updates

### PR DESCRIPTION
**Pull request by beets**
Needed for some of Roger's recent changes, both were many major versions behind. Only formatting updates.

### CODE REVIEW

**Comment by rogershijin** [comment]
Thank you so much for doing this!

**Review by shifucun — COMMENTED** [review]
Nice! Can you revert the mixer submodule change.

**Comment by beets** [comment]
> Nice! Can you revert the mixer submodule change.

Thanks - reverted! Sorry I missed that

**Comment by beets** [comment]
ptal - updated the docker image with the new packages.

**Review by shifucun — APPROVED** [review]
Looking good!

**Comment by beets** [comment]
thanks for the review!

**Pull request merged**
