### PR TITLE
[Disasters] small updates to colors and titles

### PR DESCRIPTION
**Pull request by beets**
image

### CODE REVIEW

**Comment by shifucun** [comment]
what do you think to use red for fire and yellow for drought. Blue for flood is nice now.

**Comment by beets** [comment]
wdyt?
image

**Comment by beets** [comment]
in some sense, droughts and fires co-occur, so the colors needs to have more contrast / farther apart on the color scale

**Comment by beets** [comment]
i might switch back to the originals, if you don't mind?

**Comment by shifucun** [comment]
> i might switch back to the originals, if you don't mind?

Nope, this is very subjective. As we launch, we could gather more thoughts too.

**Review by shifucun — APPROVED** [review]

**Pull request merged**
