### PR TITLE
Fix python import sorting and add lint checker (use google style)

### PR DESCRIPTION
**Pull request by shifucun**

### CODE REVIEW

**Review by pradh — APPROVED** [review]
Nice!  Will this run when we run `run_server.sh -f` ?

**Comment by shifucun** [comment]
> Nice! Will this run when we run `run_server.sh -f` ?

Yes, it will run.

**Review by beets — APPROVED** [review]
nice - better warn the team of this new feature.

**Comment by shifucun** [comment]
> nice - better warn the team of this new feature.

thanks, I will ping in chat group once this is merged

**Pull request merged**
