### PR TITLE
Add counters to fulfillment flows

### PR DESCRIPTION
**Pull request by pradh**
One dedupe bug fix in server/lib/nl/fulfillment/context.py.

I've tested it with the sample queries.

### CODE REVIEW

**Review by shifucun — APPROVED** [review]
Very nice! For adding future counters, how to find / reuse a counter key?

**Comment by pradh** [comment]
> Very nice! For adding future counters, how to find / reuse a counter key?

By looking at all references to `update_counter`?  We could define a constant for every counter, but I was trading off ease of adding it as we write code to reuse.

**Comment by pradh** [comment]
Thanks for the review!

**Comment by shifucun** [comment]
> > Very nice! For adding future counters, how to find / reuse a counter key?
> 
> By looking at all references to `update_counter`? We could define a constant for every counter, but I was trading off ease of adding it as we write code to reuse.

Yea, constant might be annoying.

**Pull request merged**
