### PR TITLE
Enable cron testing on dev

### PR DESCRIPTION
**Pull request by chejennifer**

### CODE REVIEW

**Review by shifucun — APPROVED** [review]
nice! wonder where is the Feb 29 set..

**Comment by chejennifer** [comment]
> nice! wonder where is the Feb 29 set..

what do you mean by feb 29 set?

**Comment by shifucun** [comment]
> > nice! wonder where is the Feb 29 set..
> 
> what do you mean by feb 29 set?

Where is the run schedule set?

**Comment by shifucun** [comment]
> > > > nice! wonder where is the Feb 29 set..
> > > 
> > > 
> > > what do you mean by feb 29 set?
> > 
> > 
> > Where is the run schedule set?
> 
> ohh, the run schedule is set when setting up the cron job - updated the README with this information & I've already deployed the cron testing job to dev. I could also make a change to read the schedule from the environment values yaml,, wdyt?

Setting in yaml sg!

**Pull request merged**
