### PR TITLE
Fix nlnext redirects with trailing / and query

### PR DESCRIPTION
**Pull request by pradh**
Locally, with this fix http://localhost:8080/nlnext/#q=query+string redirects to http://localhost:8080/nl/#q=query+string

### CODE REVIEW

**Review by shifucun — COMMENTED** [review]
Does /nlnext (without trailing slash) still work? I wonder if we have shared link both w/o trailing slash.

**Comment by beets** [comment]
we could keep both? with and without slash..

**Comment by pradh** [comment]
> Does /nlnext (without trailing slash) still work? I wonder if we have shared link both w/o trailing slash.

Yes, it works with and without trailing slash.

**Comment by pradh** [comment]
> we could keep both? with and without slash..

Thanks, I didn't realize we can have multiple.  I did test it works with and without slash, but added another one anyway to make it extra obvious.

**Review by shifucun — APPROVED** [review]

**Pull request merged**
