### PR TITLE
update favicon

### PR DESCRIPTION
**Pull request by chejennifer**
left is the new icon, right is the old
Screenshot 2023-07-27 at 11 10 13 AM

### CODE REVIEW

**Comment by juliawu** [comment]
Hm, in the screenshot, the left icon looks fuzzier to me than the right one. If we're making the left the new one, is that intentional?

**Comment by chejennifer** [comment]
> Hm, in the screenshot, the left icon looks fuzzier to me than the right one. If we're making the left the new one, is that intentional?

So that's the icon I got from Ido, but let me check with him ..

**Comment by chejennifer** [comment]
Updated - the one on the left is the new one 
Screenshot 2023-07-27 at 3 25 59 PM

**Review by juliawu — APPROVED** [review]
Thanks for checking!

**Pull request merged**
