### PR TITLE
Remove GKE cpu limit

### PR DESCRIPTION
**Pull request by shifucun**
Need to remove the cpu limit as the mixer would restart a few times currently when processing the stat var hierarchy cache.

### CODE REVIEW

**Review by beets — APPROVED** [review]
exciting!

**Comment by shifucun** [comment]
thanks!

**Comment by pradh** [comment]
> Need to remove the cpu limit as the mixer would restart a few times currently when processing the stat var hierarchy cache.

In your research, if there are any downsides of removing this, that might be worth noting.  (One thing that comes to mind is effect of 1 task hogging CPU on others on the same host)

**Comment by shifucun** [comment]
> > Need to remove the cpu limit as the mixer would restart a few times currently when processing the stat var hierarchy cache.
> 
> In your research, if there are any downsides of removing this, that might be worth noting. (One thing that comes to mind is effect of 1 task hogging CPU on others on the same host)

I have an open issue to later benchmark this change with A/B testing. Hopefully to come back to this when new features settle.

**Comment by pradh** [comment]
> > > Need to remove the cpu limit as the mixer would restart a few times currently when processing the stat var hierarchy cache.
> > 
> > 
> > In your research, if there are any downsides of removing this, that might be worth noting. (One thing that comes to mind is effect of 1 task hogging CPU on others on the same host)
> 
> I have an open issue to later benchmark this change with A/B testing. Hopefully to come back to this when new features settle.

Benchmark SG... but given we're making this change in prod, just wanted to check if we anticipate any issues that we should keep an eye on (e.g., based on experience on the Internets).

**Comment by shifucun** [comment]
> > > > Need to remove the cpu limit as the mixer would restart a few times currently when processing the stat var hierarchy cache.
> > > 
> > > 
> > > In your research, if there are any downsides of removing this, that might be worth noting. (One thing that comes to mind is effect of 1 task hogging CPU on others on the same host)
> > 
> > 
> > I have an open issue to later benchmark this change with A/B testing. Hopefully to come back to this when new features settle.
> 
> Benchmark SG... but given we're making this change in prod, just wanted to check if we anticipate any issues that we should keep an eye on (e.g., based on experience on the Internets).

From the current usage. The cpu usage is far below the limit. I will look into if there is alert to signal cpu issues.

image

**Pull request merged**
