### PR TITLE
deprecate userMessage

### PR DESCRIPTION
**Pull request by chejennifer**
Now that UN has switched over to using userMessages, deprecating userMessage in NL response

### CODE REVIEW

**Review by dwnoble — APPROVED** [review]

**Review by pradh — COMMENTED** [review]
To confirm, have they rolled out their client?

Otherwise, things would break if we only rollout to their backend with this change.

**Comment by chejennifer** [comment]
> They've rolled it out to their staging instance, but not prod. We could wait to merge this until it reaches prod

Ok, I can wait until it reaches prod, can you let me know?

**Review by dwnoble — COMMENTED** [review]
Will do

**Comment by dwnoble** [comment]
This PR looks good to merge. UN updated the site on their end to migrate from `userMessage` to `userMessages`, and I ran some tests locally and verified it's working for me.

**Comment by chejennifer** [comment]
> This PR looks good to merge. UN updated the site on their end to migrate from `userMessage` to `userMessages`, and I ran some tests locally and verified it's working for me.

Thank you for checking, can you approve this PR then if this looks safe?

**Review by dwnoble — APPROVED** [review]

**Pull request merged**
