### PR TITLE
Create a message json file for stat var labels

### PR DESCRIPTION
**Pull request by beets**
Converted stats_var_label into a json file for TC extraction. A follow on will be to use these messages instead of the static array.

### CODE REVIEW

**Review by tjann — COMMENTED** [review]
Did we miss e.g. https://github.com/datacommonsorg/website/blob/master/static/js/shared/stats_var_labels.ts#L23 "Median_Age_Person" ?

Should we do a grep of sorts to make sure nothing got missed?

**Comment by beets** [comment]
Thanks for catching that - good call. I did a count and that was the only one I missed.

**Comment by tjann** [comment]
> Thanks for catching that - good call. I did a count and that was the only one I missed.

Awesome. Love it when I get lucky 😆

**Review by tjann — APPROVED** [review]

**Review by shifucun — APPROVED** [review]
Any plan to do the stat var title file?

**Comment by beets** [comment]
yea, i'll do that after wrapping up place pages since it's only used in ranking pages

**Pull request merged**
