### PR TITLE
[timeline] change chart background for forecasted data

### PR DESCRIPTION
**Pull request by beets**
this pr builds off of #1093 
adds a faint, labeled data for projected data (has a baseDate). 

image

did not use emissionsScenario as a test since [1990 data does not have it set](https://autopush.datacommons.org/browser/geoId/06031?statVar=DifferenceRelativeToBaseDate1990_Daily_PrecipitationRate), though let me know if that's a bug and should be considered. here's both 2006 and 1990 base data together, with the area from 1990 onwards marked as projection.

image

### CODE REVIEW

**Comment by pradh** [comment]
> this pr builds off of #1093
> adds a faint, labeled data for projected data (has a baseDate).
> 
> image
> 
> did not use emissionsScenario as a test since [1990 data does not have it set](https://autopush.datacommons.org/browser/geoId/06031?statVar=DifferenceRelativeToBaseDate1990_Daily_PrecipitationRate), though let me know if that's a bug and should be considered. here's both 2006 and 1990 base data together, with the area from 1990 onwards marked as projection.
> 
> image

**Comment by pradh** [comment]
Sorry, I do not fully understand why stuff to the RHS of 1990 is considered projected, but on LHS?

My vague understanding is that everything here is projected.  And we sort of picked a "baseDate" to be 1990 and 2006 to compare rest of all the data points in the time-series against.

**Review by chejennifer — APPROVED** [review]
nice!

**Comment by beets** [comment]
ok, updated to:

image

**Review by pradh — APPROVED** [review]
Thanks for the update!

**Pull request merged**
