### PR TITLE
[NL] Add Extremes classifier

### PR DESCRIPTION
**Pull request by juliawu**
Adds a simple extremes classifier that looks for "extreme" or "extremes" in the query (which will be differentiated from high/low ranking).

Example:
Screenshot 2023-02-03 at 5 43 58 PM

### CODE REVIEW

**Review by pradh — COMMENTED** [review]
Hmm should we do this as a ranking classifier with EXTREME as a RankingType?

(More things might just flow downstream)

**Comment by juliawu** [comment]
> Hmm should we do this as a ranking classifier with EXTREME as a RankingType?
> 
> (More things might just flow downstream)

Sounds good! I'll make the changes and rerequest review once they're in.

**Comment by pradh** [comment]
> > Hmm should we do this as a ranking classifier with EXTREME as a RankingType?
> > (More things might just flow downstream)
> 
> Sounds good! I'll make the changes and rerequest review once they're in.

Thank you very much!

**Comment by juliawu** [comment]
Changes done! Now there's a new RankingType.EXTREME classification

Example screenshot:
Screenshot 2023-02-03 at 6 46 50 PM

**Review by pradh — APPROVED** [review]
Awesome thanks!

**Pull request merged**
