### PR TITLE
Increase Timeout to 25 secs

### PR DESCRIPTION
**Pull request by edumorlom**
I am still working on the parallel tests, so I am pushing this small update that increases timeout to 25 secs on all tests.

### CODE REVIEW

**Review by shifucun — COMMENTED** [review]
Can you make this a variable in the base test class?

**Comment by edumorlom** [comment]
I added the variable to the base test class. Ready for re-review! All tests are passing.

**Review by shifucun — APPROVED** [review]
thanks for the update!

**Comment by shifucun** [comment]
Can you do "./run_test.sh -f" to fix the lint error?

**Comment by edumorlom** [comment]
Fixed linting error. Sorry about that.

**Pull request merged**
