### PR TITLE
Move each place component into separate files.

### PR DESCRIPTION
**Pull request by beets**
There should be no other diff (other than updating React import statements).
Will need to reuse some of these components for the chart embed page, plus it's getting difficult to navigate the file.

### CODE REVIEW

**Review by shifucun — COMMENTED** [review]
This is nice, and we can conform to then lint error for "one class per file". Just a nit, can remove the "place_" prefix for all the files since they are all in the place folder?

**Comment by beets** [comment]
Sure, I renamed the files. It might make files slightly harder to find when they have generic names (chart, ranking, map) though, but this will be consistent with the python files.

**Review by shifucun — APPROVED** [review]
nice!

**Pull request merged**
