### PR TITLE
fix broken webdriver test

### PR DESCRIPTION
**Pull request by chejennifer**
- Webdriver test failure was caused by change in stat var name. Make webdriver test more reliable by finding element based on ID.
- Also realized the test is named "check statvar and uncheck" but the test only tested for checking statvar and not unchecking statvar, so added that part

### CODE REVIEW

**Comment by shifucun** [comment]
Maybe this is an example of web drive finding real data issue. I am debating weather to still let it catch the error..

**Comment by chejennifer** [comment]
> Maybe this is an example of web drive finding real data issue. I am debating weather to still let it catch the error..

There is a TAP presubmit test that should've caught this data issue so I don't think webdriver should be used for this?

**Comment by shifucun** [comment]
Ok, then we can let this focus on UI behavior. But should make it required...

**Review by shifucun — APPROVED** [review]

**Comment by chejennifer** [comment]
> Ok, then we can let this focus on UI behavior. But should make it required...

Should make what required?

**Pull request merged**
